@url = http://localhost:3000/api

POST {{url}}/users
Content-Type: application/json

{
    "name": "juanan",
    "email": "juanan@gmail.com",
    "password": "12345",
    "role": "admin"
}

### tickets no asignados
GET {{url}}/tickets/not-assigned

### tickets asignados
GET {{url}}/tickets/assigned

###
GET {{url}}/users


###
POST {{url}}/tickets
Content-Type: application/json

{
    "title": "Prueba para ver la inserción 222",
    "description": "Esto esta funcionando o no?",
    "created_by": 5
}

###
PUT {{url}}/tickets/5
Content-Type: application/json

{ 
    "title": "Prueba de actualización 2",
    "description": "A ver si esto actualiza",
    "created_by": 3
}

###
DELETE {{url}}/tickets/5

###
POST {{url}}/users/login
Content-Type: application/json

{
    "email": "juanan@gmail.com",
    "password": "12345"
}