@url = http://localhost:3000/api

POST {{url}}/users
Content-Type: application/json

{
    "name": "mario",
    "email": "mario@gmail.com",
    "password": "123456",
    "role": "admin"
}

### tickets
GET {{url}}/tickets/

###
GET {{url}}/users








###
POST {{url}}/tickets
Content-Type: application/json

{
    "title": "Tarea super urgente",
    "description": "Cambiar los botones del formulario",
    "created_by": 2
}

###
PUT {{url}}/tickets/2
Content-Type: application/json

{ 
    "title": "Prueba de actualización 2",
    "description": "A ver si esto actualiza",
    "created_by": 3
}